import {
  Americano,
  Arabe,
  Capuccino,
  Chocolate,
  Cremoso,
  Cubano,
  Gelado,
  Havaiano,
  Irlandes,
  Latte,
  Leite,
  Macchiato,
  Mocaccino,
  Tradicional,
} from '../../assets/Coffes'

export const Coffes = [
  {
    key: 1,
    img: Tradicional,
    name: 'Expresso Tradicional',
    description: 'O tradicional café feito com água quente e grãos moídos',
    price: 2.99,
    category: ['TRADICIONAL'],
    qtd: 0,
  },
  {
    key: 2,
    img: Americano,
    name: 'Expresso Americano',
    description: 'Expresso diluído, menos intenso que o tradicional',
    price: 5.39,
    category: ['TRADICIONAL'],
    qtd: 0,
  },
  {
    key: 3,
    img: Cremoso,
    name: 'Expresso Cremoso',
    description: 'Café expresso tradicional com espuma cremosa',
    price: 7.59,
    category: ['TRADICIONAL'],
    qtd: 0,
  },
  {
    key: 4,
    img: Gelado,
    name: 'Expresso Gelado',
    description: 'Bebida preparada com café expresso e cubos de gelo',
    price: 7.29,
    category: ['TRADICIONAL', 'GELADO'],
    qtd: 0,
  },
  {
    key: 5,
    img: Leite,
    name: 'Café com Leite',
    description: 'Meio a meio de expresso tradicional com leite vaporizado',
    price: 2.49,
    category: ['TRADICIONAL', 'COM LEITE'],
    qtd: 0,
  },
  {
    key: 6,
    img: Latte,
    name: 'Latte',
    description:
      'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    price: 12.99,
    category: ['TRADICIONAL', 'COM LEITE'],
    qtd: 0,
  },
  {
    key: 7,
    img: Capuccino,
    name: 'Capuccino',
    description:
      'Bebida com canela feita de doses iguais de café, leite e espuma',
    price: 6.99,
    category: ['TRADICIONAL', 'COM LEITE'],
    qtd: 0,
  },
  {
    key: 8,
    img: Macchiato,
    name: 'Macchiato',
    description:
      'Café expresso misturado com um pouco de leite quente e espuma',
    price: 11.19,
    category: ['TRADICIONAL', 'GELADO'],
    qtd: 0,
  },

  {
    key: 9,
    img: Mocaccino,
    name: 'Mocaccino',
    description: 'Café expresso com calda de chocolate, pouco leite e espuma',
    price: 13.99,
    category: ['TRADICIONAL', 'COM LEITE'],
    qtd: 0,
  },
  {
    key: 10,
    img: Chocolate,
    name: 'Chocolate Quente',
    description: 'Bebida feita com chocolate dissolvido no leite quente e café',
    price: 8.69,
    category: ['TRADICIONAL', 'COM LEITE'],
    qtd: 0,
  },
  {
    key: 11,
    img: Cubano,
    name: 'Cubano',
    description:
      'Drink gelado de café expresso com rum, creme de leite e hortelã',
    price: 11.59,
    category: ['ESPECIAL', 'ALCOÓLICO', 'GELADO'],
    qtd: 0,
  },
  {
    key: 12,
    img: Havaiano,
    name: 'Havaiano',
    description: 'Bebida adocicada preparada com café e leite de coco',
    price: 10.49,
    category: ['ESPECIAL'],
    qtd: 0,
  },
  {
    key: 13,
    img: Arabe,
    name: 'Árabe',
    description: 'Bebida preparada com grãos de café árabe e especiarias',
    price: 11.89,
    category: ['ESPECIAL'],
    qtd: 0,
  },
  {
    key: 14,
    img: Irlandes,
    name: 'Irlandês',
    description: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    price: 6.29,
    category: ['ESPECIAL', 'ALCOÓLICO'],
    qtd: 0,
  },
]
